apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/neg":"{\"ingress\":true}","meta.helm.sh/release-name":"grafana","meta.helm.sh/release-namespace":"monitoring"},"creationTimestamp":"2025-02-03T19:37:28Z","labels":{"app.kubernetes.io/instance":"grafana","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"grafana","app.kubernetes.io/version":"11.4.1","helm.sh/chart":"grafana-8.8.6"},"name":"grafana","namespace":"monitoring","resourceVersion":"515394","uid":"9ea3d667-dee4-426b-aa5a-72bd1755dd47"},"spec":{"clusterIP":"10.4.3.172","clusterIPs":["10.4.3.172"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"service","port":80,"protocol":"TCP","targetPort":3000}],"selector":{"app.kubernetes.io/instance":"grafana","app.kubernetes.io/name":"grafana"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{}}}
    meta.helm.sh/release-name: grafana
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-02-03T19:37:28Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.4.1
    helm.sh/chart: grafana-8.8.6
  name: grafana
  namespace: monitoring
  resourceVersion: "540615"
  uid: 9ea3d667-dee4-426b-aa5a-72bd1755dd47
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.4.3.172
  clusterIPs:
  - 10.4.3.172
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.44.132.43
      ipMode: VIP
